### ISSUE TITLE
列表页面优化 -  3% #已认领

### ISSUE THREAD

**Issue by tonylifepix** [tonylifepix/ezFund#3]
列表页面优化 - 3% 

-根据服务器信息，每一页最多显示10行，底部有页数选择和上下页按钮，列表按id倒序显示
-每一行显示一条申请信息，其中信息包括：申请帐号名、提交时间、摘要表格中的活动名称作为标题、下载附件word文档的超链接
-要求md卡片样式

认领请留言

**Comment by caiyexiang** [comment]
想认领，可是小小咋办= =

**Comment by caiyexiang** [comment]
认领一个吧，想到苏菲屏幕我就心疼

**Comment by tonylifepix** [comment]
随意阿= =
