### ISSUE TITLE
通过逻辑实现 5% #已认领 #已完工x

### ISSUE THREAD

**Issue by tonylifepix** [tonylifepix/ezFund#5]
-对于没有通过的项目，显示“通过”“否决”按钮。点击“通过”或者“否决”按钮，然后隐藏按钮，原位置变成已选择的状态（通过显示为绿色字体“已批准”，否决显示为红色字体“已否决”）
-对于已通过的项目，只需要显示已选择的状态（通过显示为绿色字体“已批准”，否决显示为红色字体“已否决”）
-如果通过了该申请，则该申请信息提交到团委书记帐号，团委书记的帐号才能看到这条申请信息并决定批准与否
-如果否决了该申请，团委书记将无法看到这条申请信息

认领留言

**Comment by MrFool** [comment]
认..认领？

**Comment by MrFool** [comment]
强烈要求加薪
